#!/bin/bash
#
# How to run
# cd $FlyWithLua_REPO
# ./build-XP12-Window-API-Sample_win_mac_lin_WithCmake_OnLinux

rm -r XP12WindowApiSample/win_x64/*
rm -r XP12WindowApiSample/lin_x64/*
rm -r XP12WindowApiSample/mac_x64/*


# Windows build

 rm -r build/*
 cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-x86-64.cmake
 cmake --build ./build -v
 cp ./build/win.xpl ./XP12WindowApiSample/win_x64/XP12WindowApiSample.xpl


# Linux build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build ./build -v
cp ./build/lin.xpl ./XP12WindowApiSample/lin_x64/XP12WindowApiSample.xpl


# Mac build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-x86_64-11.3.cmake
cmake --build ./build -v
cp ./build/mac.xpl ./XP12WindowApiSample/mac_x64/XP12WindowApiSample.xpl

exec $SHELL
#

